# Generated by Django 5.2.11 on 2026-02-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('EDITOR', 'Editor'), ('HYBRID', 'Hybrid'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20),
        ),
    ]
