# Generated by Django 6.0.1 on 2026-02-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('EDITOR', 'Editor'), ('HYBRID', 'Hybrid'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20),
        ),
    ]
