# Generated by Django 6.0.1 on 2026-02-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_contact_user_created_by_admin_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp_available',
            field=models.BooleanField(default=False),
        ),
    ]
