# Generated by Django 6.0.1 on 2026-02-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_whatsapp_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('DEVELOPER', 'Developer')], max_length=20, null=True),
        ),
    ]
