# Generated by Django 6.0.1 on 2026-02-23 12:11

from django.db import migrations


def populate_departments(apps, schema_editor):
    """Create initial Department records"""
    Department = apps.get_model('accounts', 'Department')
    Department.objects.get_or_create(
        name='IT',
        defaults={'description': 'Information Technology Department'}
    )
    Department.objects.get_or_create(
        name='DEVELOPER',
        defaults={'description': 'Developer Department'}
    )


def reverse_population(apps, schema_editor):
    """Remove initial departments"""
    Department = apps.get_model('accounts', 'Department')
    Department.objects.filter(name__in=['IT', 'DEVELOPER']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_department_alter_user_department'),
    ]

    operations = [
        migrations.RunPython(populate_departments, reverse_population),
    ]
