# Generated by Django 6.0.1 on 2026-02-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_is_company_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('COMPANY_ADMIN', 'Company Admin'), ('MANAGER', 'Manager'), ('EDITOR', 'Editor'), ('HYBRID', 'Hybrid'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20),
        ),
    ]
